/*$file${.::egizmo.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: egizmo.qm
* File:  ${.::egizmo.c}
*
* This code has been generated by QM 5.2.5 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #    : QPC-SP-221115A
* Issued to    : Bamboozle Technologies, Inc.
* Framework(s) : qpc
* Support ends : 2023-11-15
* License scope:
*
* Single Products:
* eGizmo Bamboozle 2nd Generation
* FooBar X123
*/
/*$endhead${.::egizmo.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
. . .
